# Generated by Django 5.0.6 on 2024-06-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_customuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='song_artist_img',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
    ]
