# Generated by Django 5.0.6 on 2024-07-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_history_song_artist_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicrequest',
            name='spotify_id',
            field=models.CharField(max_length=30),
        ),
    ]
