# Generated by Django 5.0.6 on 2024-07-03 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_musicrequest_spotify_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='song_artist_img',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='history',
            name='song_cover_url',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='likedsong',
            name='song_cover_url',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='musicresquestsong',
            name='song_cover_url',
            field=models.CharField(max_length=100),
        ),
    ]
