# Generated by Django 5.0.6 on 2024-07-04 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_alter_history_song_artist_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicrequest',
            name='item_image_url',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musicrequest',
            name='item_name',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
    ]
